development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: monte_calro_development

pruduction:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: monte_calro_test

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: monte_calro_test

